- name: Déploiement CloudNinja
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml
    - vault/secrets.yml
  roles:
    - { role: frontend, when: "'frontend' in group_names" }
    - { role: backend, when: "'backend' in group_names" }
    - { role: database, when: "'database' in group_names" }
